---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machines.mock.api.version
spec:
  group: mock.api.version
  names:
    kind: Machine
    listKind: MachineList
    plural: machines
    singular: machine
  scope: Namespaced
  versions:
    - name: alpha
      schema:
        openAPIV3Schema:
          type: object
      served: true
      storage: true
      subresources:
        status: { }
