apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.7.1+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: machine-deletion-remediation.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: machine-deletion-remediation operator
  displayName: machine-deletion-remediation
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - machine
  - deletion
  links:
  - name: Machine Deletion Remediation
    url: https://machine-deletion-remediation.domain
  maintainers:
  - email: mshitrit@redhat.com
    name: Michael Shitrit
  maturity: alpha
  provider:
    name: Michael Shitrit
  version: 0.0.1
