# permissions for end users to edit machinedeleteionremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeleteionremediation-editor-role
rules:
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeleteionremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeleteionremediations/status
  verbs:
  - get
