# permissions for end users to edit defaultremediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultremediationtemplate-editor-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - defaultremediationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - defaultremediationtemplates/status
  verbs:
  - get
