# permissions for end users to view defaultremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultremediation-viewer-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - defaultremediations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.example.com
  resources:
  - defaultremediations/status
  verbs:
  - get
