# permissions for end users to edit defaultremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultremediation-editor-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - defaultremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - defaultremediations/status
  verbs:
  - get
