# permissions for end users to edit machinedeleteionremediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeleteionremediationtemplate-editor-role
rules:
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeleteionremediationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeleteionremediationtemplates/status
  verbs:
  - get
