# permissions for end users to edit machinedeletionremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletionremediation-editor-role
rules:
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediations/status
  verbs:
  - get
