# permissions for end users to view machinedeletionremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletionremediation-viewer-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - machinedeletionremediations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.example.com
  resources:
  - machinedeletionremediations/status
  verbs:
  - get
