# permissions for end users to view machinedeletionremediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletionremediationtemplate-viewer-role
rules:
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediationtemplates/status
  verbs:
  - get
