# permissions for end users to edit machinedeletionremediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletionremediationtemplate-editor-role
rules:
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine-deletion-remediation.medik8s.io
  resources:
  - machinedeletionremediationtemplates/status
  verbs:
  - get
