apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: machine-deletion-remediation.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MachineDeletionRemediation is the Schema for the machinedeletionremediations
        API
      displayName: Machine Deletion Remediation
      kind: MachineDeletionRemediation
      name: machinedeletionremediations.machine-deletion-remediation.medik8s.io
      version: v1alpha1
    - description: MachineDeletionRemediationTemplate is the Schema for the machinedeletionremediationtemplates
        API
      displayName: Machine Deletion Remediation Template
      kind: MachineDeletionRemediationTemplate
      name: machinedeletionremediationtemplates.machine-deletion-remediation.medik8s.io
      version: v1alpha1
  description: machine-deletion-remediation operator
  displayName: machine-deletion-remediation
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespacell
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - machine
  - deletion
  links:
  - name: Machine Deletion Remediation
    url: https://machine-deletion-remediation.domain
  maintainers:
  - email: medik8s@googlegroups.com
    name: Medik8s Team
  maturity: alpha
  provider:
    name: Medik8s
    url: https://github.com/medik8s
  version: 0.0.0
