name: Pre Submit
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version-file: 'go.mod' 
        cache-dependency-path: 'go.sum' 

    - name: Build
      run: make manager

    - name: Test
      run: make test

#    - name: Run codacy-coverage-reporter
#      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}  --language go --force-coverage-parser go -r cover.out

    - name: TestMutations
      run: make test-mutation-ci
